apiVersion: v1
kind: ServiceAccount
metadata:
  name: default-ingress-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-ingress-controller-clusterRole
rules:
  - apiGroups: [""]
    resources: ["services", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list", "update"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-ingress-controller-clusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dubbo-kubernetes-ingress-controller-clusterRole
subjects:
  - kind: ServiceAccount
    name: dubbo-kubernetes-ingress-controller
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-kubernetes-ingress-controller
  namespace: default
  labels:
    app: ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-controller
  template:
    metadata:
      labels:
        app: ingress-controller
    spec:
      hostNetwork: true
      serviceAccountName: default-kubernetes-ingress-controller
      containers:
      - name: default-kubernetes-ingress-controller
        image: docker.io/mfordjody/default-ingress-controller:test
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: default
spec:
  controller: "sample.io/default-ingress-controller"
